import { Anonymous_Pro } from "next/font/google";
import "./globals.css";
import { CartProvider } from '@/contexts/CartContext';
import { CartNotificationProvider } from '@/contexts/CartNotificationContext';



const anonymous = Anonymous_Pro({
  variable: "--font-anon",
  subsets: ["latin"],
  weight: ["400", "700"],
  display: "swap"
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${anonymous.variable} antialiased`}
      >
        <CartProvider>
          <CartNotificationProvider>
            {children}
          </CartNotificationProvider>
        </CartProvider>
      </body>
    </html>
  );
}
